### PR TITLE
cpu notifier

### PR DESCRIPTION
**Pull request by LON3WO7F**
Solved issue #64

### CODE REVIEW

**Comment by LON3WO7F** [comment]
Hey @mani1soni 
Please review

**Comment by mani1soni** [comment]
You are adding this in Shell-Scripts Folder...I think this is Python's Code so you need to add this script in python's folder....can you plz do the same and again create PR, then i'll merge it.

**Comment by LON3WO7F** [comment]
> You are adding this in Shell-Scripts Folder...I think this is Python's Code so you need to add this script in python's folder....can you plz do the same and again create PR, then i'll merge it.

Hey @mani1soni 
What to do next.
Still facing the same issue.

**Comment by mani1soni** [comment]
No worries....i'll solve and merge

**Pull request merged**
